name: Python CI

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.10'
        type: string
      ruff-config:
        description: 'Path to ruff config file'
        required: false
        default: 'pyproject.toml'
        type: string
      bandit-config:
        description: 'Path to bandit config file'
        required: false
        default: 'pyproject.toml'
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Run Ruff linter and formatter
      run: |
        ruff check . --config ${{ inputs.ruff-config }}

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit[toml]
    - name: Run Bandit security check with detailed report
      run: |
        bandit -c ${{ inputs.bandit-config }} -r ./ -f html -o bandit-report.html
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
            bandit-report.html

  pr-status-check:
    runs-on: ubuntu-latest
    needs: [lint, security]
    steps:
      - name: PR is ready to be merged
        run: |
          echo "All checks passed! PR is ready to be reviewed and merged."
